CREATE TABLE USER(
  	ID INT NOT NULL AUTO_INCREMENT,
  	NAME VARCHAR(50),
  	SURNAME VARCHAR(50),
  	USERNAME VARCHAR(50) NOT NULL,
  	PASSWORD VARCHAR(50) NOT NULL,
  	EMAIL VARCHAR(50) NOT NULL,
  	PRIMARY KEY (ID),
  	UNIQUE (EMAIL),
  	UNIQUE (USERNAME)
  );
  CREATE TABLE RESTAURANT(
  	ID INT NOT NULL AUTO_INCREMENT,
  	NAME VARCHAR(50) NOT NULL,
  	TYPE VARCHAR(50),
  	PRIMARY KEY (ID)
  );
  CREATE TABLE USER_VS_RESTAURANT(
  	ID INT NOT NULL AUTO_INCREMENT,
  	USER INT NOT NULL,
  	RESTAURANT INT NOT NULL,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (USER) REFERENCES USER(ID),
  	FOREIGN KEY (RESTAURANT) REFERENCES RESTAURANT(ID)
  );
  CREATE TABLE MENU(
  	ID INT NOT NULL AUTO_INCREMENT,
  	NAME VARCHAR(50) NOT NULL,
  	RESTAURANT INT NOT NULL,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (RESTAURANT) REFERENCES RESTAURANT(ID)
  );
  CREATE TABLE MENU_SECTION(
  	ID INT NOT NULL AUTO_INCREMENT,
  	NAME VARCHAR(50) NOT NULL,
  	MENU INT NOT NULL,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (MENU) REFERENCES MENU(ID)
  );
  CREATE TABLE SECTION_ITEM(
  	ID INT NOT NULL AUTO_INCREMENT,
  	NAME VARCHAR(50) NOT NULL,
  	MENU_SECTION INT NOT NULL,
  	PRICE VARCHAR(30),
  	PRIMARY KEY (ID),
  	FOREIGN KEY (MENU_SECTION) REFERENCES MENU_SECTION(ID)
  );
  CREATE TABLE PENDING_REQUEST(
  	ID INT NOT NULL AUTO_INCREMENT,
  	TIME DATETIME  NOT NULL,
  	USER INT NOT NULL,
  	RESTAURANT INT NOT NULL,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (USER) REFERENCES USER(ID),
  	FOREIGN KEY (RESTAURANT) REFERENCES RESTAURANT(ID)
  );
  CREATE TABLE DONE_REQUEST(
  	ID INT NOT NULL AUTO_INCREMENT,
  	PENDING_ID INT NOT NULL,
  	TIME DATETIME  NOT NULL,
  	USER INT NOT NULL,
  	RESTAURANT INT NOT NULL,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (PENDING_ID) REFERENCES PENDING_REQUEST(ID),
  	FOREIGN KEY (USER) REFERENCES USER(ID),
  	FOREIGN KEY (RESTAURANT) REFERENCES RESTAURANT(ID)
  );